aws_region = "eu-west-3"

cluster_name = "prueba-it-eks"

domain_name = "abdo-devops.com"

db_username = "wpuser"
# db_password is auto-generated by Terraform and stored in AWS Secrets Manager
db_name     = "wordpress"

ecr_name = "mi-ecr-de-prueba"

alert_email = "alerts@abdo-devops.com"
