apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: wordpress-db-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: wordpress-db-secrets
    creationPolicy: Owner
  data:
  - secretKey: db-host
    remoteRef:
      key: SECRET_NAME_PLACEHOLDER
      property: host
  - secretKey: db-user
    remoteRef:
      key: SECRET_NAME_PLACEHOLDER
      property: username
  - secretKey: db-password
    remoteRef:
      key: SECRET_NAME_PLACEHOLDER
      property: password
  - secretKey: db-name
    remoteRef:
      key: SECRET_NAME_PLACEHOLDER
      property: dbname

---

apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-secrets-manager
spec:
  provider:
    aws:
      service: SecretsManager
      region: eu-west-3
